// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDm2MuGoNT2Zuk8q_6Xic0n4r34bjvzJA',
    appId: '1:1008616728963:web:f1664421e53d9abc936eb6',
    messagingSenderId: '1008616728963',
    projectId: 'taskverse-43d3e',
    authDomain: 'taskverse-43d3e.firebaseapp.com',
    storageBucket: 'taskverse-43d3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Zan57q52oFtm12xTyB89kvPQ-BGher8',
    appId: '1:1008616728963:android:21d24eb91c6105c1936eb6',
    messagingSenderId: '1008616728963',
    projectId: 'taskverse-43d3e',
    storageBucket: 'taskverse-43d3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBowORTz8pZCOT3roeq3kGC9yG1gl1bbHo',
    appId: '1:1008616728963:ios:b10d470093486a5b936eb6',
    messagingSenderId: '1008616728963',
    projectId: 'taskverse-43d3e',
    storageBucket: 'taskverse-43d3e.firebasestorage.app',
    iosBundleId: 'com.example.taskverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBowORTz8pZCOT3roeq3kGC9yG1gl1bbHo',
    appId: '1:1008616728963:ios:b10d470093486a5b936eb6',
    messagingSenderId: '1008616728963',
    projectId: 'taskverse-43d3e',
    storageBucket: 'taskverse-43d3e.firebasestorage.app',
    iosBundleId: 'com.example.taskverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDm2MuGoNT2Zuk8q_6Xic0n4r34bjvzJA',
    appId: '1:1008616728963:web:db5f27482160e46a936eb6',
    messagingSenderId: '1008616728963',
    projectId: 'taskverse-43d3e',
    authDomain: 'taskverse-43d3e.firebaseapp.com',
    storageBucket: 'taskverse-43d3e.firebasestorage.app',
  );
}
